### PR TITLE
Finish up for 0.1 already

### PR DESCRIPTION
**Pull request by Lokathor**
* [x] Timers
* [x] Keypad
* [x] Interrupt
* [x] PALRAM
* [x] VRAM
* [x] OAM

### CODE REVIEW

**Comment by ketsuban** [comment]
For `KEYINPUT` I think I'd rather declare it as `ROVolAddress<u16>`, and then provide a struct defined with the [bitflags](https://crates.io/crates/bitflags) macro. While that does require the end user to invert the value they read from `KEYINPUT` themselves, this isn't an onerous requirement since it only has to happen once, at the point of reading the register itself.

```rust
use gba_hal::Buttons;
use gba_hal::mmio;

struct State {
    pressed: Buttons,
    held: Buttons,
    released: Buttons,
}

impl State {
    fn read_keypad(&mut self) -> Self {
        let then = self.held;
        let now = Buttons::from_bits_truncate(!mmio::KEYINPUT.read());
        self.pressed = now & !then;
        self.held = now;
        self.released = then & !now;
    }

    fn is_pressed(&self, buttons: Buttons) -> bool {
        self.pressed.contains(buttons)
    }
}
```

Doing this with `KeyInput` is laborious...

```rust
let pressed = KeyInput::new()
    .with_a_released(now.a_released() & !then.a_released())
    .with_b_released(now.b_released() & !then.b_released())
// ...
    .with_l_released(now.l_released() & !then.l_released());
```

...because it doesn't implement arithmetic traits like the bitflags macro.

**Comment by Lokathor** [comment]
Yeah, the raw version is laborious as heck to use. It's not really meant to be used directly honestly. I was going to make the inner value `pub` and then people can get it out and flip it themselves if they want, and we'll also have the existing type in the `gba` crate, which will have a `From` impl that correctly inverts the lowest 10 bits and so on.

**Comment by Lokathor** [comment]
Alright, the VRAM stuff is very slight because it's hard to cover all 6 modes properly, but more stuff can always be layered on top by a higher level crate.

I think we're good if you think we're good.

**Comment by Lokathor** [comment]
OAM has to be split up because otherwise it's undefined what happens to the Affine param values in between the OAM entries when you write an OAM value

**Comment by Lokathor** [comment]
not sure what happened there

bors r+

**Pull request merged**
